version: 2

jobs:
  fetch:
    docker: &docker
      - image: circleci/node:14.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Node version
          command: node -v
      - run:
          name: Fetch deps
          command: yarn
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/three-vrm/node_modules
            - packages/types-vrm-0.0/node_modules
            - packages/types-vrmc-materals-mtoon-1.0/node_modules
            - packages/types-vrmc-vrm-1.0/node_modules

  build:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Build
          command: yarn build

  test:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Test
          command: yarn test

  lint:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Lint
          command: yarn lint

  docs:
    docker: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - deps-
      - run:
          name: Docs
          command: yarn docs

workflows:
  version: 2
  inspection:
    jobs:
      - fetch
      - build:
          requires:
            - fetch
      - test:
          requires:
            - fetch
      - lint:
          requires:
            - fetch
      - docs:
          requires:
            - fetch
